### ISSUE TITLE
How to commit offset manually?

### ISSUE THREAD

**Issue by chrislee87** [confluentinc/kafka-connect-hdfs#127]
After kafka-connect-hdfs write data to hdfs, I load the data file into hive warehouse use 'LOAD DATA INPATH ...' which remove the original data file.
Howerver the latest offset is stored in data file's name, and Kafka-connect commit offset periodically(e.x. offset.flush.interval.ms=60000). If kafka-connect-hdfs restart, it may get the wrong offset from kafka, which causes data duplicate.
I want to commit offset manually after a data file is created, any suggestions?
See the code below, from TopicPartitionWriter.java

```
String directoryName = FileUtils.directoryName(url, topicsDir, directory);
if (!storage.exists(directoryName)) {
  storage.mkdirs(directoryName);
}
storage.commit(tempFile, committedFile);
startOffsets.remove(encodedPartiton);
offset = offset + recordCounter;
recordCounter = 0;
log.info("Committed {} for {}", committedFile, tp);

// commit offset && load data file into hive warehouse
```

**Comment by chrislee87** [comment]
Even I commit offset(add this line **context.offset(tp, endOffset+1);** in **commitFile**) before loading hdfs file to hive warehouse, after restarting kafka-connect-hdfs, still get the wrong offset.

**Comment by chrislee87** [comment]
**context.offset** has no effect, incluing in the code below, it will not reset kafka-connect's offset.

  private void resetOffsets() throws ConnectException {
    if (!recovered) {
      readOffset();
      if (offset > 0) {
        log.debug("Resetting offset for {} to {}", tp, offset);
        context.offset(tp, offset);
      }
      recovered = true;
    }
  }

**Comment by sandeep265** [comment]
If this is true does it mean that we can never reset the offset and recovery will never work as expected? Is this a bug in Kafka Connect code?

**Comment by chrislee87** [comment]
Latest offset is stored in data file's name. if those files are moved, you can save the offset in a sepratre file. @sandeep265

**Comment by sandeep265** [comment]
@chrislee87 In your previous comment you've mentioned that context.offset has no effect. Let's say I know the correct offset.  Will I never be able reset to the correct offset given that context.offset doesn't work according to you?

**Comment by cotedm** [comment]
@chrislee87 I'm curious why you need to rename the files when this connector supports integration with Hive. Is there a missing piece there that leads you to need to do this? If so, it may just make sense to add that piece rather than trying to manually commit offsets. 

@sandeep265 offset recovery does work if you haven't renamed the files in HDFS. Specifically, if you haven't renamed the latest file that was written. Upon recovering the state, the connector reads the file name of the latest file created in the output directory and uses the offset there to recover the proper position. The issue here is that the file is being renamed and @chrislee87 is trying to manually recover the offset for future data to come in which is currently not possible.

**Comment by n-petrachkov** [comment]
@cotedm one of the use cases to move or rename files is to have some kind of a compaction process that would merge small files, generated by kafka connect instance, into a bigger file. Hive integration does not help with this. _Estimation that there might be a million small files (100 kb - 300 kb) just from one data source._

**Comment by ewencp** [comment]
@n-petrachkov I think you have to be careful about doing this with Hive to avoid duplicates, but you should be able to safely compact files as long as you use consistent naming. It should be safe because all we do to recover the last offset is list the files under a partition and take the one with the largest offset. As long as the last file written has the largest offset in the filename, you should be fine. In fact, you should even be able to use this to compact and *move* the files elsewhere -- offset recovery should just work as long as you always leave at least the last file in place.

**Comment by n-petrachkov** [comment]
@ewencp thank you the the explanation.
We will take this behaviour into account.

**Comment by kkonstantine** [comment]
Closing since the above explanation seems sufficient, and also because since https://github.com/confluentinc/kafka-connect-hdfs/pull/305 was merged the connector can additionally check consumer offsets in the absense of files in HDFS.
