### ISSUE TITLE
Partitioner is a public interface but can't be freely used

### ISSUE THREAD

**Issue by dossett** [confluentinc/kafka-connect-hdfs#180]
Since `Partitioner` is a public interface anyone can implement it, but the ConnectorConfig only allows specific instances and subclasses of specific instances:

https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java#L378-L392

Perhaps Partitioner should not be public or the ConnectorConfig should be more lenient.

**Comment by cdemeijer** [comment]
:+1: Nice catch. I recently implemented the Partitioner interface and after initial grumbling about the lack of documentation on the interface got it to work as expected.
Since my Partitioner does seem to be working (on 3.1.2) I dug a bit deeper and it seems that the exception is only used to create error messages.

Overall I agree with your conclusion but would like to keep my partitioner so I would vote for removing the last <code>else</code> part:
https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/HdfsSinkConnectorConfig.java#L390-L391

(Oh and document the interface ofcourse).

**Comment by ewencp** [comment]
Yeah, this looks like the else clause should really just return `false`. Since this is in the recommender, I'm assuming this is only an issue when hitting the validation endpoint or do we hit this during regular parsing of the config?

**Comment by cdemeijer** [comment]
Sorry for the late reply. I didn't run into the problem @dossett mentioned since I only discovered the validation endpoint today and my setup is currently broken after upgrading to 3.3.0.
If the recommender were used during regular parsing of the config files I would expect this to show up somewhere in the logs right? Since I'm using a custom Partitioner implementation?

And not to hijack this thread, but was the Partitioner interface intended to be public?

**Comment by kkonstantine** [comment]
Hey everyone, 

recently the recommender now used for the HDFS connector was updated to become more lenient indeed. Would you be interested in attempting to try your partitioners with what is currently merged to master for both the kafka-connect-hdfs and kafka-connect-storage-common repos?

Here are the related lines that should allow validation of custom partitioners: https://github.com/confluentinc/kafka-connect-storage-common/blob/master/partitioner/src/main/java/io/confluent/connect/storage/partitioner/PartitionerConfig.java#L254-L257

**Comment by kkonstantine** [comment]
As mentioned above, this appears not to be an issue anymore. Closing.
