### ISSUE TITLE
Sink Avro data without schema registry

### ISSUE THREAD

**Issue by codenamelxl** [confluentinc/kafka-connect-hdfs#183]
I'm having a problem with sinking a topic formatted in avro to hdfs. I can confirmed that my avro data is correctly formatted. However, it is not an option to use schema registry to push correct avro format for the AvroConverter (appending schema id to the data).
Is there any other way to work around this issue?
It would be best if i can select the schema from a file and Force the Converter to not search for schema-id inside the data.

**Comment by ewencp** [comment]
@codenamelxl This is actually more about the AvroConverter (found in confluentinc/schema-registry) than the HDFS connector. [Converters](http://docs.confluent.io/3.2.0/connect/concepts.html#converters) are the component responsible for translating between Kafka and Connect's generic data API before the data is passed to the connector.

Currently the converter only supports serialization/deserialization using the schema registry. It would certainly be possible to extend it to use specific schemas via configuration (whether loaded from a file or just included directly in the config). However, I wouldn't be that inclined to support this -- it doesn't work out well in practice because you need the *exact* Avro schema you encoded with to decode the data. If you use this approach, you can't ever [evolve the schema](http://docs.confluent.io/3.2.0/avro.html) for the topic, which means you can never change the format of the data. This is pretty crippling since it means you need to switch topics every time you want to, e.g., add one more field to the schema.

**Comment by codenamelxl** [comment]
Thanks for your answer. I'm fully aware that schema registry provides me with a real nice schema evolve feature. However, i'm stuck with normal avro encoding without schema id. Logstash does not have a codec to support this. I took a look at file stream source but it does not have the capability to parse the log like i can do with logstash filter. This is off topic but maybe you can show me any log collector that support schema registry.
Thanks again.

**Comment by ewencp** [comment]
@codenamelxl What I was trying to point out is that your particular issue doesn't have to do with the HDFS connector (or any other connector, for that matter) at all. Connect intentionally differentiates between how data is read from Kafka and deserialized (Converters) and how it gets translated to other systems (connectors).

If you want support for something like this, it is more appropriately provided via the confluentinc/schema-registry project, where the serializers/deserializers are located. It can be a bit confusing since there are multiple components involved (Kafka itself, AvroConverter in schema-registry, the HDFS connector itself, and finally anything downstream consuming HDFS files). But I think the right place to direct these issues is schema-registry (if you think the serializers should provide a schema-registry-free serialization) or you'd need an alternative set of serializers that handle the approach to serialization that you are suggesting (and which Confluent serializers don't currently support, with good reason described more [here](http://docs.confluent.io/3.2.0/avro.html)).

**Comment by codenamelxl** [comment]
Got your point. I asked in the wrong place. I kinda like the idea of schema registry so i think i will try to write a codec for logstash that support schema registry. I'm gonna go ahead and close this issue. Thanks for your help.
