### ISSUE TITLE
Scaling Workers Doesn't Improve Performance

### ISSUE THREAD

**Issue by chenchik** [confluentinc/kafka-connect-hdfs#210]
I want to build a dynamically scaling kafka connect cluster which builds more workers as latency increases so they push data to hdfs faster. So, the further the timestamp is on the last read file from the current epoch time, the more workers I want to invoke. I want to scale workers such that performance increases to catch up to the kafka data pipeline and have my hdfs cluster be as "current" as possible.

I understand that when you scale workers, they share the load that kafka is giving them. Is there a way to keep their individual performance the same but increase total performance by adding a worker?

I'm measuring performance in this way:

- First, I make an empty Kafka topic with a replication factor of 1 and 3 partitions.

- I'm using openshift, so I initialize the kafka-connect docker image for a distributed worker with these configurations:

```
config.storage.topic=****
rest.port=8083
values.converter.schemas.enable=false
group.id=connect_group_multi_worker
key.converter.schemas.enable=false
key.converter=org.apache.kafka.connect.storage.StringConverter
offset.storage.topic=****
bootstrap.servers=****
value.converter=org.apache.kafka.connect.storage.StringConverter
status.storage.topic=****
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
rest.advertised.host.name=connect15
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
```

- Then I initialize instances of hdfs connectors using the rest API. I use Postman to submit POST requests to http://myip/connectors, they look like this:

```
{
    "name": "hdfs-1000000-worker-1",
    "config": {
        "connector.class": "io.confluent.connect.hdfs.HdfsSinkConnector",
        "tasks.max": "3",
        "topics": "mytopic",
        "hdfs.url": "****",
        "flush.size": "1000",
        "logs.dir": "/logs",
        "key.converter":"org.apache.kafka.connect.storage.StringConverter",
	"value.converter":"org.apache.kafka.connect.storage.StringConverter",
        "schemas.enable":false
    }
}
```

- I can confirm the existence of the connector by sending a GET request.

- Then I fill up the topic I made previously by pumping in numbers 1 to 1,000,000 into the topic as a producer using the command `seq 1 1000000` as input into the topic.

- Once the worker stops working, I check the creation times of the first and last files in the topic in HDFS. 

- If first and last files have close timestamps, performance is good, if the difference is great, performance is poor (depending on the job)

------------------------------------------------------------------------------------------
**results**
------------------------------------------------------------------------------------------

**1)** I've tried running the job with one worker, one connector, and 3 tasks and have had the best performance.

**2)** Second best is one worker, multiple hdfs connectors pointing to the same hdfs cluster, 3 tasks for each connector.
- multiple connectors were made using the rest api and simply changing their names in the POST requests.

**3)** Third best result was made by using two workers on two seperate apps/services on openshift. Each worker had one connector and 3 tasks each. Each connector in this case had a **different** `group.id`. Using the same `group.id` caused errors.

**4)** The worst result came from running 1 worker, 1 connector, and 3 tasks, and scaling the worker using the openshift "replication factor". This created two instances of the same worker, with the same connector, each having 3 tasks.
- Although I have been able to confirm that CPU load on each worker does go down in this case.

-----------------------------------------------------------------

I think there may be a way of scaling I don't know about or a worker property that I haven't found. What should I do if I don't want to decrease the CPU load on my containers/workers when adding more workers?

**Comment by ewencp** [comment]
How much data actually results from the random data you've generated? 1,000,000 records doesn't sound like much, so a lot of the perf numbers you're gathering could be noise and/or outweighed by other costs that are effectively constant, but relatively large for the size of your dataset.

Result 1 is kind of expected. Since you have exactly as many tasks as there are topic partitions (which is how work will be balanced across tasks), and presumably you have more than enough bandwidth and CPU to handle those 3 tasks, a single worker is in a sense ideal here because you won't spend any extra time doing any rebalancing or anything like that. In fact, running that in standalone mode might even show a bit of an improvement.

Result 2 doesn't sound like it isn't copying the same amount of data. In this case did you split data between different topics or something? e.g. 3 topics w/ 1 partition each only? Otherwise, it seems like you might be copying the same data multiple times, so the total amount of work is different.

Result 3 seems like it has the same problem -- if you have 2 connectors, aren't you copying 2x as much data.

Result 4's approach won't really help you unless you have more partitions to work with -- if there's only one connector with a maximum of 3 tasks, you haven't increased the number of threads processing that data, so unless on one worker you hit the capacity of the worker, I wouldn't expect to see any performance benefit.

In general, I'd suggest doing long running tests, i.e. just run the producer the whole time you run the consumer, or at least for a lot longer so you get at least a few minutes worth of data. I'd also suggest making sure you're saturating *some* resource before looking at scaling. If you increase the number of workers but there's no resource under sufficient demand, I wouldn't expect to see an interesting difference in performance -- just some noise across measurements.

**Comment by chenchik** [comment]
I tried limiting CPU consumption per container in Openshift and saw explicit increases in performance running the same test. The runs took between 20 minutes to 2 minutes. 

1 worker had the worst performance and time to write all the files decreased with an increase in pods (workers).
