### ISSUE TITLE
Unable to write data from client node to name node

### ISSUE THREAD

**Issue by sgswathi** [confluentinc/kafka-connect-hdfs#320]
Hi,
I am running connector as a root and hapoop file system is own by hdfs user
So from root user(client node) we are not able to write data to hdfs file system(name node)

How can I resolve this,Kindly do reply @DimaD  @travisjeffery @ijuma @ @mhowlett @astubbs @

**Comment by rhauch** [comment]
First, please don't @-notify particular people on these issues. Second, this issue is more of a question than reporting a problem with the code: did you ask in another forum, such as the Confluent Slack community or discussion forum?

Hadoop runs in [two modes](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsPermissionsGuide.html):
* simple that uses the operating system to determine the user
* [secured with Kerberos](https://hadoop.apache.org/docs/r2.8.0/hadoop-project-dist/hadoop-common/SecureMode.html). 

If you're using the simple mode, you may have to have a user on the HDFS host system that matches the user on the client system, and uses ACLs defined in Hadoop/HDFS. Simple is by definition a simple mechanism, and may not work in all situations.

Please see the [HDFS connector documentation](https://docs.confluent.io/current/connect/connect-hdfs/docs/index.html), and in particular the [configuration documentation](https://docs.confluent.io/current/connect/connect-hdfs/docs/configuration_options.html#security) for the properties that control the principals used for various activities.
