### ISSUE TITLE
Kafka connect hdfs creating +tmp with replication 3 ignoring the hdfs-site.xml replication config which is set as 1

### ISSUE THREAD

**Issue by abhisheksahani** [confluentinc/kafka-connect-hdfs#461]

**Comment by ncliang** [comment]
This is surprising. You can see the code in [DataWriter](https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/DataWriter.java#L223) where we create the temp directory. We don't do anything special and just ask HDFS FileSystem API to create it for us.
One thing though. Did you recently decrease the replication factor in hdfs-site.xml from 3 to 1? My understanding is that this will affect only new files and directories created since the [change](https://community.cloudera.com/t5/Support-Questions/Replication-factor-not-changed-in-HDFS-from-hdfs-site-xml/td-p/217100).

**Comment by abhisheksahani** [comment]
@ncliang there was some permission issues because of which hdfs client in connector was not getting initialized with the properties we specified in hdfs path instead its taking the default  replication factor. it was my bad.
