### ISSUE TITLE
NUMERIC type turns to BINARY after importing from DB2 to HIVE

### ISSUE THREAD

**Issue by litianxing** [confluentinc/kafka-connect-hdfs#48]
In db2 data type is numeric, but the data is imported into the hive through the confluent into a binary,
and hive field type is binary

**Comment by Ishiihara** [comment]
@litianxing I think this should be fixed in the JDBC connector. Currently, the JDBC connector is converting numeric type to bytes. We may add features to handle numeric type in the future releases of the JDBC connector. Related issue in the JDBC connector: https://github.com/confluentinc/kafka-connect-jdbc/issues/31

**Comment by Ishiihara** [comment]
Closing this issue as it should be fixed in the JDBC source connector.
