### ISSUE TITLE
Exactly once requirements

### ISSUE THREAD

**Issue by tulinski** [confluentinc/kafka-connect-hdfs#485]
Hello,

While looking at other connectors I noticed that for instance [kafka-connect-s3](https://docs.confluent.io/current/connect/kafka-connect-s3/index.html) puts some limitations on `Partitioner` in order to preserve exactly-once semantics:
https://docs.confluent.io/current/connect/kafka-connect-s3/index.html#s3-exactly-once
Is exactly-once always ensured in case of `kafka-connect-hdfs`?

Regards,
Tomek

**Comment by ncliang** [comment]
@tulinski the same limitation will apply here for exactly once delivery. You will notice that the limitation is only for `TimeBasedPartitioner` to guarantee deterministic timestamp extraction and rotation. This more or less means that when something bad happens and we need to replay from an offset in the topic, we get deterministic replay results.

I would say this is not so much limitation of the connectors, per se, since the connector does the best it can to record offsets last written and available in HDFS/S3. If something catastrophic happens, it tries to recover from last written offset. Rather, I would say that this is a limitation on configuration that may result in non-deterministic replay of the topic.

It may be productive to explain what you are trying to achieve with `TimeBasedPartitioner` and see if there is a way to do it while not invalidating exactly-once guarantees?

**Comment by tulinski** [comment]
@ncliang, thanks for a prompt response, I was wondering about differences/similarities between HDFS and S3 connectors in terms of delivery semantics. I found [this thread](https://groups.google.com/forum/#!topic/confluent-platform/0a2vmEKQViE) helpful.
Maybe I am missing something, but after studying WAL implementation in HDFS connector I am pretty sure that it preserves exactly-once even for non-deterministic partitioners.

**Comment by ncliang** [comment]
@tulinski as you say, the WAL file in HDFS implementation will preserve exactly once schematics. I was thinking of a fringe example of partitioner depending on timestamp and crash/recover on a different machine with different clock due to clock drift. But, even in that case, the WAL will ensure that recovery happens correctly. The partition for a given message might be slightly different due to the clock drift, but messages should not be duplicated or missed due to the WAL and offset topic. My mistake was to confuse the partitioner partition and the TopicPartition partition :-p

If this answers your question, I think we can close this issue?

**Comment by tulinski** [comment]
@ncliang sure, the issue can be closed, thanks.
