### ISSUE TITLE
Major: Kafka Connect needs to work with JSON input data records

### ISSUE THREAD

**Issue by rekhajoshm** [confluentinc/kafka-connect-hdfs#74]
Kafka Connect to work with JSON input data records.
Currently kafka connect to hdfs sinkconnector works with AVRO and parquet format inputs.
There needs to JSONReader/Writer as well.

**Comment by rekhajoshm** [comment]
@ewencp Are there any known and current accepted approaches to sending JSON input data to hdfs? thanks.

**Comment by 13h3r** [comment]
We are using simple plaintext `Format` that serializes data to hdfs and separate them with `\n`. I can publish it if you are interested in it

**Comment by rekhajoshm** [comment]
Thanks @13h3r for your response , would be interested to check it out, please publish. thanks.

**Comment by 13h3r** [comment]
I will do it this week

**Comment by derricks** [comment]
Add me to the list of folks interested in seeing an example of this.

**Comment by blbradley** [comment]
@13h3r please share soon!

**Comment by deepakpengoria** [comment]
@13h3r please share

**Comment by 13h3r** [comment]
I am trying to pull this off from our project. Here it is very first extracted version - https://github.com/2gis/kafka-connect-hdfs-ext

The idea is pretty straight forward - just dump all messages into hdfs and separate the messages by `\n`

I plan to migrate to maven, write docs soon and release it to bintray on this week.

**Comment by blbradley** [comment]
@13h3r Thanks for sharing! Why don't you submit a PR? Probably easier than rolling your own package.

**Comment by blbradley** [comment]
@ewencp I'm pinging you because you've answered on the Google Group before.

I tried going through the quick start using `JsonConverter` for keys and values, schemas disabled, and the default format class. There are no errors thrown, and the log shows successful recovery. Yikes!

```
[2016-07-07 23:46:53,204] INFO Successfully joined group connect-hdfs-sink with generation 1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:434)
[2016-07-07 23:46:53,204] INFO Setting newly assigned partitions [test_hdfs_json-0] for group connect-hdfs-sink (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:219)
[2016-07-07 23:46:53,211] INFO Started recovery for topic partition test_hdfs_json-0 (io.confluent.connect.hdfs.TopicPartitionWriter:193)
[2016-07-07 23:46:53,217] INFO Finished recovery for topic partition test_hdfs_json-0 (io.confluent.connect.hdfs.TopicPartitionWriter:208)
[2016-07-07 23:46:56,368] INFO Reflections took 4675 ms to scan 260 urls, producing 11972 keys and 78895 values  (org.reflections.Reflections:229)
```

There should be some files written to HDFS in this log excerpt if it was truly successful.

**Comment by ewencp** [comment]
@blbradley What does this have to do with this bug?

**Comment by blbradley** [comment]
@ewencp I felt that using those settings would be a possible way to get JSON data in Kafka topics to work (before seeing this issue) after reading Confluent's docs.

The lack of error messages from those settings are definitely another issue.

**Comment by ewencp** [comment]
@blbradley I'm not sure I understand the issue you're raising. The connector always does a recovery step as part of its startup process. This is true even the first time you run it. Recovery here just means scanning to check what files have been delivered, if there is an outstanding tempfile that still needs to be copied to its final location, etc. If this is the first run, we'll still log that we started trying to recover and finished, but it will effectively be a noop since the directory we're delivering to will be empty.

**Comment by blbradley** [comment]
@ewencp The issue is that nothing is written to HDFS with those settings, and there is no indicator that there is a problem. That is the part of the log where the HDFS connector would write to HDFS.

I'll be filing an issue with more details soon.

**Comment by blbradley** [comment]
Should `StringConverter` work for this? It seems semantically correct but does not work.

**Comment by blbradley** [comment]
I got `StringConverter` to work in #131 if anyone wants to try it. It will collect your JSON strings!

**Comment by bharatviswa504** [comment]
@blbradley 
We have only JsonConverter packaged in Kafka, could you please provide some information to make it work for Kafka topic JSON data to export to HDFS.

Thanks,
Bharat

**Comment by blbradley** [comment]
@bharatviswa504 StringConverter is packaged with Kafka Connect. It is in available at `org.apache.kafka.connect.storage.StringConverter`.

You must build the PR above and then use `org.apache.kafka.connect.storage.StringConverter` has the key or value converter in a Kafka Connect config.

**Comment by bharatviswa504** [comment]
@blbradley checked wrong folder. Yes it is available. With that PR, if kafka topic has json data with out schema it will convert as String (toConnectData) and it will work?

**Comment by blbradley** [comment]
Yes! It does require some manual work: moving jars into the right place on top of Confluent's packaging and compiling two projects. But it works!

**Comment by bharatviswa504** [comment]
Compile 2 projects, change is only in kafka-connect-hdfs only right?
Is there something I am missing

**Comment by blbradley** [comment]
Please read #131 thoroughly. You have to build schema-registry also.

**Comment by bharatviswa504** [comment]
@blbradley Thanks for info. Ya missed one more PR referenced.

**Comment by cotedm** [comment]
@rekhajoshm since you originally opened this, can you confirm if you can use schemaless JSON after the merge of #176? It isn't clear to me what kind of JSON input we're looking at for your use case and what the expected output should be. With #176 you can take schemaless JSON as input and write it out using the `AvroFormat` by way of the `StringConverter` if you wanted, but if you can clarify what your needs are that would be helpful.

**Comment by rekhajoshm** [comment]
@cotedm - I am on avro now. Closing this as both #131 and #176 are in. Thanks to everyone involved.
