### ISSUE TITLE
Failed on local exception: com.google.protobuf.InvalidProtocolBufferException

### ISSUE THREAD

**Issue by nravich2** [confluentinc/kafka-connect-hdfs#93]
I am just trying to replicate quickstart tutorial given in http://docs.confluent.io/3.0.0/connect/connect-hdfs/docs/hdfs_connector.html#quickstart

However , I run into InvalidProtocolBufferException when i try to read data from a topic  to HDFS in my cluster.
Can I get some help on finding out the root cause of this issue?

**Comment by bjornhjelle** [comment]
I had this issue and solved it by opening up for access on port 8020 to the Amazon EMR master node where my Hadoop cluster runs.
Trying to figure out other issues now...

**Comment by cotedm** [comment]
`InvalidProtocolBufferException` is typically because of a problem communicating to the NameNode. Mostly this comes from using the wrong port to try and reach the NameNode. If there is a specific concern, please go ahead and post the full error message and we'll try and help out @nravich2. We can reopen if that's the case. Thanks!
