### ISSUE TITLE
TimeBasedPartitioner according to specified field

### ISSUE THREAD

**Issue by kerkero** [confluentinc/kafka-connect-hdfs#98]
Please add the ability to have time based partitioning by specific field denoting the event time (instead of ingestion time)

**Comment by xianzhen** [comment]
I used fieldPartioner to handle it. But i think your idea is better!

**Comment by doriwal** [comment]
Agree that timeBased  should have the option to use event time , for example event that send from mobile SDK at 8:58 might be pushed to kafka at 9:01 , using the ingestion time is not accurate 

I also added pull request in order to support several fieldsPartitioner as in my use case I need both event time and event type in order to partition the events in parquet

**Comment by ewencp** [comment]
@xianzhen `FieldPartitioner` only works for exact values, which means you can't use a timestamp field directly, you need it to be simplified to, e.g., minute, hour, or day, depending on the granularity you want.

@kerkero I think this would definitely be valuable. In particular, Kafka added timestamps natively in its format (but after this connector was originally created) so we should at least support those. Additionally, since Connect supports timestamp logical types, we should definitely have support for those fields. I think this should amount to a small additional config to specify the field and minor modifications to `TimeBasedPartitioner`.

**Comment by doriwal** [comment]
Agree that FieldPartitioner cant use timestamp , in my use case each event that i am sending to kafka contains also the following fields : day like 2016-08-23 , time like 10:00 
this fields are calculated from the event timestamp (I am adding day/time fields to the event that i am sending to kafka)

**Comment by codenamelxl** [comment]
A little head-up, it seems that kafka-connect-hdfs has been change to use [kafka-connect-storage-common](https://github.com/confluentinc/kafka-connect-storage-common) which does have a very nice way to provide a timestamp field ( it can be seen [here](http://docs.confluent.io/current/connect/connect-storage-cloud/kafka-connect-s3/docs/configuration_options.html) in kafka-connect-s3 which also use kafka-connec-storage-common. We now have to wait to this change come into release :)

**Comment by kkonstantine** [comment]
Indeed, timestamp-based partitioners where timestamp is stored in the Kafka record or a record field have become available under `kafka-connect-storage-common`. 

Two recent PRs have added support of such partitioners in the HDFS connector (https://github.com/confluentinc/kafka-connect-hdfs/pull/245 and https://github.com/confluentinc/kafka-connect-hdfs/pull/246). 

Closing this issue, and we may reopen this one or a new one if there's an issue with these partitioners. Anyone interested in field-based timestamp partitioning is highly encouraged to try what's on master right now! Thanks everyone for highlighting this feature!
